name: Get File Date

on:
  workflow_dispatch:

jobs:
  get_date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo

      - name: Get file date
        run: |
          git log --diff-filter=A --format="%cd" --date=iso-strict --find-copies-harder -1 -- "repo/DeviceImages/200/LAIP12P128SL.jpg"