name: Get File Date

on:
  workflow_dispatch:

jobs:
  get_date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo

      - name: Get file date
        working-directory: ./repo
        run: |
          date=$(git log --format="%cd" --date=iso-strict --find-copies-harder -1 -- "DeviceImages/200/LAIP12P128SL.jpg")
          echo "File date: $date"