name: Upload Images By Type

on:
  workflow_dispatch:
    inputs:
      script_file:
        description: "Select the script to run"
        required: true
        default: "runAllScripts.js"
        type: choice
        options:
          - "uploadAccessoryImagesToContentful.js"
          - "uploadSwatchesToContentful.js"
          - "uploadImagesToContentful.js"
          - "runAllScripts.js"

jobs:
  upload-to-np:
    name: Upload to Non-Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Debug and List Scripts
        run: ls -l src/scripts  # Ensure the scripts exist

      - name: Run Selected Script in NP
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          ENVIRONMENT_ID: ${{ secrets.CONTENTFUL_PT_ENV_ID }}
          ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: |
          echo "Running script: ${{ github.event.inputs.script_file }}"
          node src/scripts/${{ github.event.inputs.script_file }}

  upload-to-prod:
    name: Upload to Prod
    runs-on: ubuntu-latest
    needs: upload-to-np
    environment:
      name: Prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Selected Script in Prod
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          ENVIRONMENT_ID: ${{ secrets.CONTENTFUL_PROD_ENV_ID }}
          ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
        run: |
          echo "Running script: ${{ github.event.inputs.script_file }}"
          node src/scripts/${{ github.event.inputs.script_file }}
